// src/types/email.ts

export enum EmailTemplateType {
  // --- EMAILS DA PLATAFORMA ---
  PLATFORM_NEW_COMPANY_WELCOME = 'PLATFORM_NEW_COMPANY_WELCOME',
  PLATFORM_NEW_COMPANY_ADMIN_WELCOME = 'PLATFORM_NEW_COMPANY_ADMIN_WELCOME',
  PLATFORM_PASSWORD_RESET = 'PLATFORM_PASSWORD_RESET',
  PLATFORM_INDEPENDENT_PARTICIPANT_WELCOME = 'PLATFORM_INDEPENDENT_PARTICIPANT_WELCOME',
  
  // --- EMAILS DA EMPRESA (ACIONADOS POR EVENTOS) ---
  COMPANY_EVENT_REGISTRATION_CONFIRMATION = 'COMPANY_EVENT_REGISTRATION_CONFIRMATION',
  
  // Acionados pela mudança de estado da inscrição
  COMPANY_REGISTRATION_STATUS_PENDING = 'COMPANY_REGISTRATION_STATUS_PENDING',
  COMPANY_REGISTRATION_STATUS_AWAITING_PAYMENT = 'COMPANY_REGISTRATION_STATUS_AWAITING_PAYMENT',
  COMPANY_REGISTRATION_STATUS_APPROVED = 'COMPANY_REGISTRATION_STATUS_APPROVED',
  COMPANY_REGISTRATION_STATUS_REJECTED = 'COMPANY_REGISTRATION_STATUS_REJECTED',
  COMPANY_REGISTRATION_STATUS_CANCELLED = 'COMPANY_REGISTRATION_STATUS_CANCELLED',
  
  // Acionados por agendamento ou manualmente
  COMPANY_POST_EVENT_THANK_YOU = 'COMPANY_POST_EVENT_THANK_YOU',
  COMPANY_EVENT_REMINDER = 'COMPANY_EVENT_REMINDER',
  
  // Acionados manualmente (Campanhas)
  COMPANY_MARKETING_NEWSLETTER = 'COMPANY_MARKETING_NEWSLETTER',
}