// src/types/email.ts

export enum EmailTemplateType {
  // --- EMAILS DA PLATAFORMA ---
  PLATFORM_NEW_COMPANY_WELCOME = 'PLATFORM_NEW_COMPANY_WELCOME',
  PLATFORM_NEW_COMPANY_ADMIN_WELCOME = 'PLATFORM_NEW_COMPANY_ADMIN_WELCOME',
  PLATFORM_PASSWORD_RESET = 'PLATFORM_PASSWORD_RESET',
  PLATFORM_INDEPENDENT_PARTICIPANT_WELCOME = 'PLATFORM_INDEPENDENT_PARTICIPANT_WELCOME',
  
  // --- EMAILS DA EMPRESA (ACIONADOS POR EVENTOS) ---
  COMPANY_EVENT_REGISTRATION_CONFIRMATION = 'COMPANY_EVENT_REGISTRATION_CONFIRMATION',
  
  // Acionados pela mudança de estado da inscrição
  COMPANY_REGISTRATION_STATUS_PENDING = 'COMPANY_REGISTRATION_STATUS_PENDING',
  COMPANY_REGISTRATION_STATUS_AWAITING_PAYMENT = 'COMPANY_REGISTRATION_STATUS_AWAITING_PAYMENT',
  COMPANY_REGISTRATION_STATUS_APPROVED = 'COMPANY_REGISTRATION_STATUS_APPROVED',
  COMPANY_REGISTRATION_STATUS_REJECTED = 'COMPANY_REGISTRATION_STATUS_REJECTED',
  COMPANY_REGISTRATION_STATUS_CANCELLED = 'COMPANY_REGISTRATION_STATUS_CANCELLED',

  EVENT_REGISTRATION_APPROVED = 'EVENT_REGISTRATION_APPROVED',
  EVENT_REMINDER_24H = 'EVENT_REMINDER_24H',
  EVENT_FEEDBACK_REQUEST = 'EVENT_FEEDBACK_REQUEST',
  
  // Acionados por agendamento ou manualmente
  COMPANY_POST_EVENT_THANK_YOU = 'COMPANY_POST_EVENT_THANK_YOU',
  COMPANY_EVENT_REMINDER = 'COMPANY_EVENT_REMINDER',
  
  // Acionados manualmente (Campanhas)
  COMPANY_MARKETING_NEWSLETTER = 'COMPANY_MARKETING_NEWSLETTER',

  // --- EMAILS DO MÓDULO DE SUPORTE ---
  SUPPORT_TICKET_CREATED = 'SUPPORT_TICKET_CREATED',
  SUPPORT_NEW_REPLY = 'SUPPORT_NEW_REPLY',
  SUPPORT_TICKET_CLOSED = 'SUPPORT_TICKET_CLOSED',

  // --- EMAILS DO MÓDULO DE AGENDAMENTOS ---
  SCHEDULING_CONFIRMATION = 'SCHEDULING_CONFIRMATION',
  SCHEDULING_CANCELLATION = 'SCHEDULING_CANCELLATION',
  SCHEDULING_REMINDER = 'SCHEDULING_REMINDER',
  SCHEDULING_RESCHEDULED = 'SCHEDULING_RESCHEDULED',
}