// frontend/src/types/file.ts
export enum FilePurpose {
  EVENT_BANNER = 'EVENT_BANNER',
  EVENT_DOCUMENT = 'EVENT_DOCUMENT',
  COMPANY_SLIDESHOW = 'COMPANY_SLIDESHOW',
  COMPANY_SIGNATURE_IMAGE = 'COMPANY_SIGNATURE_IMAGE',
  COMPANY_LOGO = 'COMPANY_LOGO',
  POLICY_DOCUMENT = 'POLICY_DOCUMENT',
  DISPLAY_SLIDESHOW = 'DISPLAY_SLIDESHOW',
  KIOSK_LOGO = 'KIOSK_LOGO',
  DISPLAY_LOGO = 'DISPLAY_LOGO',
  SUPPORT_ATTACHMENT = 'SUPPORT_ATTACHMENT',
  CERTIFICATE_TEMPLATE = 'CERTIFICATE_TEMPLATE', 
}