// frontend/src/types/file.ts
export enum FilePurpose {
  EVENT_BANNER = 'EVENT_BANNER',
  EVENT_DOCUMENT = 'EVENT_DOCUMENT',
  COMPANY_SLIDESHOW = 'COMPANY_SLIDESHOW',
  COMPANY_SIGNATURE_IMAGE = 'COMPANY_SIGNATURE_IMAGE',
  PLATFORM_SIGNATURE_IMAGE = 'PLATFORM_SIGNATURE_IMAGE',
  COMPANY_LOGO = 'COMPANY_LOGO',
  POLICY_DOCUMENT = 'POLICY_DOCUMENT',
  DISPLAY_SLIDESHOW = 'DISPLAY_SLIDESHOW',
  KIOSK_LOGO = 'KIOSK_LOGO',
  DISPLAY_LOGO = 'DISPLAY_LOGO',
  SUPPORT_ATTACHMENT = 'SUPPORT_ATTACHMENT',
  CERTIFICATE_TEMPLATE = 'CERTIFICATE_TEMPLATE', 
  PLATFORM_BACKGROUND_IMAGE = 'PLATFORM_BACKGROUND_IMAGE',
  
  HOMEPAGE_LOGO = 'HOMEPAGE_LOGO',
  HOMEPAGE_SHARE_IMAGE = 'HOMEPAGE_SHARE_IMAGE',
  HOMEPAGE_HERO_IMAGE = 'HOMEPAGE_HERO_IMAGE',
  HOMEPAGE_SLIDESHOW = 'HOMEPAGE_SLIDESHOW',
  HOMEPAGE_EVENT_IMAGE = 'HOMEPAGE_EVENT_IMAGE',

  CORRESPONDENCE_INBOX = 'CORRESPONDENCE_INBOX', // Ficheiros associados a um registo de correspondência (ex: anexos de um email recebido)
  CORRESPONDENCE_OUTBOX = 'CORRESPONDENCE_OUTBOX', // Ficheiros associados a um registo de correspondência (ex: anexos de um email enviado)
  CORRESPONDENCE_DOCUMENT = 'CORRESPONDENCE_DOCUMENT',
}